language: go
go:
- 1.13.x
jobs:
  include:
  - stage: test
    script: make build test
  - stage: publish
    script: make release && ./.travis.gcs-publish.sh
stages:
- test
- name: publish
  if: branch = master AND type = push
notifications:
  slack:
    secure: ePDQefRJ5NpUAiVTN+6QL2XQ3Qx74HDShO4uTE+O2xMmJdcDOqy4OlvRZdSltatBgPrYq006qRNLqYSakpcAHCsGH/p44SMTSCwfwccRsztOuMN6O/71TzX5cwz//jfZgBx8/Qrz15ULm1xvZ1StkSq9apENkbweASOp7oe68g3OfVQ3iYuLdEoClrFyg1U9smPb1nzFU2tPHJ6Yt01aD5kI6ImkTZZSd6y8Dcu0xdO1LNBfbWA18WB7Hea4z5KHRCzgY5OFqPm85lFDkVF9ykPuqO1n5Si9SglSx5mLWzeNuy1C8gT7E8AATuQvVYsQ8Pq6z4ukDobAnAzHBjXwasMFToLxpvb6tmk0f16qCn4RNwR9q2ccy7T1x/rpBXEV9VNjWh/ZJtqPMGEvYoyjJ48R3GcqbqAJVA1p0SZQJITAvC/q8/PCkAb3wf0M1WGQntxWdTeMR7EO5aocF+kaeJoF1J6/L+s2mHK+XP8KSNThMlmeLfdMh2NIp7TAdX6KWQhqiSGYdoHn7qarf0e1VURoD3xMVkOFX5sQoLDW8XoI0yUvx+5iROVFnlUccaMoctKwHSDOmaa48OzK3bsG3AVm4ca3MxYujldipZwxzuNGBPAplVfPhW0GJzeasbSAq+n94DkC6DNUgZNXEpAiEAtItKittGhtU0YBeAvBAFs=
