name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: actions/setup-go@v2.1.1
      with:
        go-version: '1.13'
    - name: Build & Test
      run: make build test

  publish:
    needs: test
    if: |
      github.event_name == 'push' && (
        github.ref == 'refs/heads/main' || (
          startsWith(github.ref, 'refs/heads/v') && endsWith(github.ref, 'x')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: gcloud auth
        run: |
          gcloud config set disable_prompts True
          gcloud auth activate-service-account --key-file <(echo $GCLOUD_CLIENT_SECRET | base64 --decode)
        env:
          GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
      - name: Build release
        run: make release
      - name: Publish artifacts
        run: .github/workflows/gcs-publish.sh
